### ISSUE TITLE
General inquiry 

### ISSUE THREAD

**Issue by Loonyy** [Gnat008/PerWorldInventory#133]
Is there a way to make a world have the same inventory as my main world?

**Comment by sloanr333** [comment]
I apologize in advance for a brief answer. I'm a bit pressed for time, but I'll do what I can.

The answer should be on the plugin page here: https://www.spigotmc.org/resources/per-world-inventory.4482/

In particular, take a look at the worlds.yml spoiler. You can see that multiple worlds are in a group in that example; when the worlds are in a group together they will share inventories.

**Comment by Loonyy** [comment]
It's fine, thanks for the response!

Yeah that's what I thought, however I did that and the world still has a separate inventory. Here's the config:
```

  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    - spawn
    default-gamemode: SURVIVAL
```

**Comment by sloanr333** [comment]
1) Is that your whole config file? If so, you're missing the "groups:" on the first line.
2) Did you run "pwi reload" command either from console or as command after changing the file?

**Comment by Loonyy** [comment]
No it isn't my whole config, this is:
```
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    - spawn
    default-gamemode: SURVIVAL
   creative:
     worlds:
     - plotworld
     default-gamemode: CREATIVE
```

I restarted the server, /pwi reload didn't seem to do anything.

**Comment by sloanr333** [comment]
Hmm. And you don't get errors or warnings in the server logs when PWI loads? It looks like there's an extra space character before the last few lines, starting with the "creative:" line. I know YaML is super picky about junk like that, but I don't know if this is why. I imagine if the worlds file is getting errors or ignored, it would default to thinking that every world should be separate. It should be defaulting to whatever you have set in config.yml for "share-if-unconfigured", but if there's an error I don't know what it would do.

**Comment by ljacqu** [comment]
Good eye, @sloanr333, [YAMLint](http://www.yamllint.com/) is indeed not happy with the config.

**Comment by sloanr333** [comment]
Ooh that's a nice tool! I was just using sublime text with view white space on. haha

**Comment by Loonyy** [comment]
Nope, no errors and nah, that's just from when I pasted the code in. It added an extra space

**Comment by sloanr333** [comment]
Can you paste your config? and possibly a list of plugins? Maybe there's something else happening here

**Comment by Loonyy** [comment]
Sure dude.
worlds.yml:
```
# In this file you define your groups and the worlds in them.
# Follow this format:
# groups:
#   default:
#     worlds:
#     - world
#     - world_nether
#     - world_the_end
#     default-gamemode: SURVIVAL
#   creative:
#     worlds:
#     - plotworld
#     default-gamemode: CREATIVE
#
# 'default' and 'creative' are the names of the groups
# worlds: is a list of all worlds in the group
# If you have 'manage-gamemodes' set to true in the main config, the server
# will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    - spawn
    default-gamemode: SURVIVAL
   creative:
     worlds:
     - plotworld
     default-gamemode: CREATIVE
```
config.yml:
```
##########################################
#  PerWorldInventory configuration file  #
#                                        #
#  If new values are added to the        #
#  config, they will not automatically   #
#  be added here. They will default to   #
#  false if not present.                 #
##########################################

# Version of the config.
# When updating config, copy the new verison number here.
# Only ever change when adding new config options!
# Used to notify administrators on config updates.
config-version: 4

# If true, the server will change player's gamemodes when entering a world
# The gamemode set is configured in the worlds.yml file
manage-gamemodes: false

# If true, players will have different inventories for each gamemode
separate-gamemode-inventories: true

# If true, any worlds that are not in the worlds.yml configuration file will share the same inventory
share-if-unconfigured: false

# All settings for players are here:
player:
  # Save and Load players' economy balances. Requires Vault!
  economy: false
  # Load players' ender chests
  ender-chest: true
  # Load players' inventory
  inventory: true
  # All options for player stats are here:
  stats:
    # Load if a player is able to fly
    can-fly: true
    # Load the player's display name
    display-name: false
    # Load a player's exhaustion level
    exhaustion: true
    # Load how much exp a player has
    exp: true
    # Load a player's hunger level
    food: true
    # Load if a player is flying
    flying: true
    # Load what gamemode a player is in. This is shadow-set to false if
    # 'manage-gamemodes' is true, to stop infinite loop
    gamemode: false
    # Load how much health a player has
    health: true
    # Load what level the player is
    level: true
    # Load all the potion effects of the player
    potion-effects: true
    # Load the saturation level of the player
    saturation: true
    # Load a player's fall distance
    fall-distance: true
    # Load the fire ticks a player has
    fire-ticks: true
    # Load the maximum amount of air a player can have
    max-air: true
    # Load the current remaining air a player has
    remaining-air: true

# Config Version 2 below this line #

# Configure the amount of time between saves, in seconds
# Default is 5 minutes (300 seconds)
save-interval: 300

# Config Version 3 Additions below this line #

# Attempt to figure out which world a player last logged off in
# and save/load the correct data if that world is different.
# REQUIRES MC 1.9.2 OR NEWER
load-data-on-join: false

# Print out debug messages to the console for every event that happens in PWI
debug-mode: false

# Config Version 4 additions below this line #

# Disables bypass regardless of permission
# Defaults to false
disable-bypass: false
```

plugins:
http://imgur.com/a/Zalaz
