### ISSUE TITLE
WDLCompanion incompatibility

### ISSUE THREAD

**Issue by SlimeDog** [Gnat008/PerWorldInventory#241]
Spigot 1.12
PWI 1.10.0
WDLCompanion 1.1.3

With WDLC set to deny copying (PWI configuration available if needed), lost inventory in the world into which I connected.

WDLCompanion/config.yml (comments elided):
```
wdl:
  logMode: none
  requestDuration: 3600
  canDoNewThings: false
  canDownloadInGeneral: false
  saveRadius: -1
  canCacheChunks: false
  canSaveEntities: true
  canSaveTileEntities: true
  canSaveContainers: true
  sendEntityRanges: true
  requestMessage: ""
  chunkOverrides:
  per-world:
```
