### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by FrankHeijden** [Gnat008/PerWorldInventory#301]
World1; survival
World2; creative

Player in gamemode 1 switches in World2 switches to World1 and is being set into gamemode 0, but keeps his gamemode 1 World2 inventory 

pwi 11.4

**Comment by FrankHeijden** [comment]
```
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL
  creative:
    worlds:
    - creative
    default-gamemode: SURVIVAL
```
